export type ApplicationErrorCode =
  | "UNAUTHENTICATED"
  | "ONBOARDING_REQUIRED"
  | "ACCOUNT_INACTIVE"
  | "FORBIDDEN"
  | "NOT_FOUND"
  | "VALIDATION_FAILED"
  | "INVALID_STATE_TRANSITION"
  | "INTERNAL_ERROR"
  | "JOB_NOT_FOUND"
  | "JOB_NOT_DRAFT"
  | "JOB_NOT_AVAILABLE"
  | "APPLICATION_ALREADY_EXISTS"
  | "APPLICATION_NOT_FOUND"
  | "APPLICATION_NOT_SUBMITTED"
  | "APPLICATION_NOT_WITHDRAWABLE"
  | "CONCURRENT_ACCEPTANCE_CONFLICT"
  | "CONCURRENT_COMPLETION_CONFLICT"
  | "FIRST_OPPORTUNITY_INELIGIBLE"
  | "AGREEMENT_NOT_ACTIVE"
  | "CODE_INVALID"
  | "CODE_EXPIRED"
  | "CODE_LOCKED"
  | "WORK_NOT_CHECKED_OUT"
  | "ACTIVE_REPORT_BLOCKS_COMPLETION"
  | "CREDIT_NOT_AVAILABLE"
  | "JOB_NOT_PUBLISHED"
  | "JOB_NOT_OWNED"
  | "BOOST_ALREADY_ACTIVE"
  | "IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_INPUT"
  | "REPORT_NOT_FOUND"
  | "REPORT_NOT_REVIEWING"
  | "REPORT_ALREADY_EXISTS"
  | "RATE_LIMITED"
  | "CATEGORY_NOT_ALLOWED"
  | "WAGE_GUIDELINE_UNAVAILABLE"
  | "WAGE_BELOW_GUIDELINE";

export class ApplicationError extends Error {
  readonly code: ApplicationErrorCode;
  readonly details?: unknown;

  constructor(code: ApplicationErrorCode, message: string, details?: unknown) {
    super(message);
    this.name = "ApplicationError";
    this.code = code;
    this.details = details;
  }
}
